.PHONY: clean All

All:
	@echo "----------正在构建项目：[ ax329x_sdk - Debug ]----------"
	@$(MAKE) -f  "ax329x_sdk.mk" && $(MAKE) -f  "ax329x_sdk.mk" PostBuild
clean:
	@echo "----------正在清理项目：[ ax329x_sdk - Debug ]----------"
	@$(MAKE) -f  "ax329x_sdk.mk" clean
